<a href="https://colab.research.google.com/github/axelmartinezportillo/elt-data-pipeline/blob/main/notebook_corredores/ETL_Corredores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url="https://raw.githubusercontent.com/axelmartinezportillo/elt-data-pipeline/refs/heads/main/datos/raw/corredores.csv"
df = pd.read_csv(url)
df.head()

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

In [3]:
#EXPLORACION DE DATOS
print("1. Primeras filas del archivo:")
display(df.head())

print("\n2. Estructura y Tipos de Datos:")
df.info()

print("\n3. Conteo de Valores Nulos por Columna:")
print(df.isnull().sum())

print("\n4. Valores únicos en la columna 'zona' (Para detectar espacios):")
print(df['zona'].unique())

print("\n5. Valores únicos en 'nivel' (Para detectar inconsistencias):")
print(df['nivel'].unique())

1. Primeras filas del archivo:

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

2. Estructura y Tipos de Datos:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               63 non-null     object
 3   nivel              68 non-null     object
 4   anios_experiencia  76 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 3.3+ KB

3. Conteo de Valores Nulos por Columna:
id_corredor           0
nombre                0
zona                 17
nivel                12
anios_experiencia     4
dtype: int64

4. Valores únicos en la columna 'zona' (Para detectar espacios):
['Paracentral' '  Centro  ' 'Centro' nan 'Occidente' 'Costa' 'Oriente']

5. Valores únicos en 'nivel' (Para detectar inconsistencias):
['Mid' 'Junior' 'SENIOR ' 'Senior' 'Elite' nan ' junior']

In [4]:
#LIMPIEZA DE DATOS
# 1. Limpieza de columnas
corredores_limpio = df.copy()
corredores_limpio.columns = corredores_limpio.columns.str.strip().str.lower()

# 2. Limpieza de strings y estandarización
for col in corredores_limpio.select_dtypes(include='object').columns:
    corredores_limpio[col] = corredores_limpio[col].astype(str).str.strip()

if 'zona' in corredores_limpio.columns:
    corredores_limpio['zona'] = corredores_limpio['zona'].str.lower()
if 'nivel' in corredores_limpio.columns:
    corredores_limpio['nivel'] = corredores_limpio['nivel'].str.lower()

# 3. Reemplazar vacíos y el texto 'nan' por Nulos reales
corredores_limpio = corredores_limpio.replace(r'^\s*$', pd.NA, regex=True)
corredores_limpio = corredores_limpio.replace('nan', pd.NA)

# 4. Duplicados
corredores_limpio = corredores_limpio.drop_duplicates()

print("Limpieza completada con éxito.")
display(corredores_limpio.head())

Limpieza completada con éxito.

   id_corredor               nombre         zona   nivel  anios_experiencia
0            1    José López Flores  paracentral     mid                4.0
1            2    José Ortiz García       centro  junior                0.0
2            3   María Ramírez Cruz       centro  senior                6.0
3            4  Fernanda Rojas Cruz         <NA>  senior                8.0
4            5      Ana Gómez Rojas         <NA>  senior                4.0

In [5]:
#Separación de Datos Válidos y Rechazados
# Definimos las columnas clave para la validación
columnas_clave = ['zona', 'nivel', 'anios_experiencia']

# Registros válidos: aquellos que no tienen valores nulos en las columnas clave
validos = corredores_limpio[
    corredores_limpio[columnas_clave].notna().all(axis=1)
].copy()

In [6]:
# Registros rechazados: aquellos que tienen al menos un valor nulo en las columnas clave
rechazados = corredores_limpio[
    corredores_limpio[columnas_clave].isna().any(axis=1)
].copy()

print(f"Total de registros: {len(corredores_limpio)}")
print(f"Registros válidos: {len(validos)}")
print(f"Registros rechazados: {len(rechazados)}")

print('\nPrimeras filas de registros válidos:')
display(validos.head())

print('\nPrimeras filas de registros rechazados:')
display(rechazados.head())

Total de registros: 80
Registros válidos: 50
Registros rechazados: 30

Primeras filas de registros válidos:

   id_corredor                 nombre         zona   nivel  anios_experiencia
0            1      José López Flores  paracentral     mid                4.0
1            2      José Ortiz García       centro  junior                0.0
2            3     María Ramírez Cruz       centro  senior                6.0
5            6  Sofía Reyes Hernández    occidente   elite                3.0
7            8  Paula Ortiz Hernández       centro  junior               17.0

Primeras filas de registros rechazados:

    id_corredor                nombre       zona   nivel  anios_experiencia
3             4   Fernanda Rojas Cruz       <NA>  senior                8.0
4             5       Ana Gómez Rojas       <NA>  senior                4.0
6             7  Pedro Vásquez Torres      costa    <NA>                1.0
9            10    Juan Cruz Castillo  occidente    <NA>                7.0
10           11   José Morales Flores       <NA>  junior                NaN

In [7]:
#MOTIVO DE RECHAZO
def motivo_rechazo_corredor(row):
    motivos = []

    # Verificar las columnas clave que usamos para definir los rechazados
    if pd.isna(row['zona']):
        motivos.append("zona_vacia")

    if pd.isna(row['nivel']):
        motivos.append("nivel_vacio")

    if pd.isna(row['anios_experiencia']):
        motivos.append("anios_experiencia_vacio")

    return ",".join(motivos)

# Aplicar la función para crear la nueva columna 'motivo_rechazo'
rechazados["motivo_rechazo"] = rechazados.apply(motivo_rechazo_corredor, axis=1)

print('\nRegistros rechazados con su motivo:')
display(rechazados.head())

Registros rechazados con su motivo:

,id_corredor,nombre,zona,nivel,anios_experiencia,motivo_rechazo
3,4,Fernanda Rojas Cruz,<NA>,senior,8.0,zona_vacia
4,5,Ana Gómez Rojas,<NA>,senior,4.0,zona_vacia
6,7,Pedro Vásquez Torres,costa,<NA>,1.0,nivel_vacio
9,10,Juan Cruz Castillo,occidente,<NA>,7.0,nivel_vacio
10,11,José Morales Flores,<NA>,junior,NaN,"zona_vacia,anios_experiencia_vacio"

In [8]:
#EXPORTAR ARCHIVOS
validos.to_csv("corredores_curated.csv", index=False)
rechazados.to_csv("corredores_rejects.csv", index=False)

print("¡Archivos generados exitosamente!")

¡Archivos generados exitosamente!

In [9]:
#CONECTAR RENDER
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:6r5AQWoE44HrllVAUznGZiLVeK6jjHfX@dpg-d6qu5ochg0os73b4g0v0-a.oregon-postgres.render.com/etl_seguros_fv1v"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 47.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [10]:
#CARGAR EN POSTGRE
# Cargar registros válidos en la tabla 'corredores_curated'
validos.to_sql(
    'corredores_curated',
    engine,
    if_exists='append',
    index=False
)

print("Registros válidos cargados exitosamente en 'corredores_curated'.")

Registros válidos cargados exitosamente en 'corredores_curated'.

In [11]:
# Cargar registros rechazados en la tabla 'corredores_rejects'
rechazados.to_sql(
    'corredores_rejects',
    engine,
    if_exists='append',
    index=False
)

print("Registros rechazados cargados exitosamente en 'corredores_rejects'.")

Registros rechazados cargados exitosamente en 'corredores_rejects'.

In [12]:
print('Primeras 10 filas de la tabla corredores_curated:')
display(pd.read_sql(
    "SELECT * FROM corredores_curated LIMIT 10",
    engine
))

Primeras 10 filas de la tabla corredores_curated:

   id_corredor                 nombre         zona   nivel  anios_experiencia
0            1      José López Flores  paracentral     mid                4.0
1            2      José Ortiz García       centro  junior                0.0
2            3     María Ramírez Cruz       centro  senior                6.0
3            6  Sofía Reyes Hernández    occidente   elite                3.0
4            8  Paula Ortiz Hernández       centro  junior               17.0
5            9  Carlos Torres Vásquez  paracentral  junior                2.0
6           13  Valeria García Torres      oriente  senior               23.0
7           14     Diego Gómez Chávez       centro  senior               20.0
8           16     Juan Reyes Morales        costa  junior                6.0
9           18     Paula Pérez Flores      oriente     mid               23.0

In [13]:
print('\nPrimeras 10 filas de la tabla corredores_rejects:')
display(pd.read_sql(
    "SELECT * FROM corredores_rejects LIMIT 10",
    engine
))

Primeras 10 filas de la tabla corredores_rejects:

,id_corredor,nombre,zona,nivel,anios_experiencia,motivo_rechazo
0,4,Fernanda Rojas Cruz,None,senior,8.0,zona_vacia
1,5,Ana Gómez Rojas,None,senior,4.0,zona_vacia
2,7,Pedro Vásquez Torres,costa,None,1.0,nivel_vacio
3,10,Juan Cruz Castillo,occidente,None,7.0,nivel_vacio
4,11,José Morales Flores,None,junior,NaN,"zona_vacia,anios_experiencia_vacio"
5,12,Pedro Gómez Vásquez,None,mid,21.0,zona_vacia
6,15,Fernanda Cruz Reyes,centro,mid,NaN,anios_experiencia_vacio
7,17,Jorge Reyes Ramírez,None,elite,20.0,zona_vacia
8,20,Pedro Cruz Pérez,None,junior,24.0,zona_vacia
9,21,Juan Hernández Pérez,oriente,None,21.0,nivel_vacio